### PR TITLE
Add fuzzing corpuses

### PR DESCRIPTION
**Pull request by MykolaMykhno**

### CODE REVIEW

**Comment by markus-oberhumer** [comment]
upx-testsuite is frozen, so please create a new repository `upx-testsuite-v3` and document the LICENSE of the test file.

**Comment by markus-oberhumer** [comment]
BTW there is also https://github.com/upx/upx-testsuite-v2

**Comment by jreiser** [comment]
I want to download and apply this PullRequest to my local working directory first, before deciding whether to integrate with the rest of UPX sources on GitHub.  So, I try:
```
$  gh --version
gh version 2.36.0 (2023-10-04)
https://github.com/cli/cli/releases/tag/v2.36.0

$ gh auth login
? What account do you want to log into? GitHub.com
? What is your preferred protocol for Git operations? HTTPS
? Authenticate Git with your GitHub credentials? Yes
? How would you like to authenticate GitHub CLI? Paste an authentication token
Tip: you can generate a Personal Access Token here https://github.com/settings/tokens
The minimum required scopes are 'repo', 'read:org', 'workflow'.
? Paste your authentication token: ****************************************
- gh config set -h github.com git_protocol https
✓ Configured git protocol
✓ Logged in as jreiser

$ gh pr checkout 3
GraphQL: Could not resolve to a PullRequest with the number of 3. (repository.pullRequest)

$ ls .git
branches        config       FETCH_HEAD  HEAD   index  logs     objects    packed-refs
COMMIT_EDITMSG  description  gitk.cache  hooks  info   modules  ORIG_HEAD  refs

$ cat .git/config   ## every git command knows the repository shown below, but 'gh' does not.
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = https://github.com/upx/upx.git
	fetch = +refs/heads/*:refs/remotes/origin/*
<<snip>>


```
That fails, because I did not get any diffs, sources, etc.  What should I do instead?

**Comment by markus-oberhumer** [comment]
@jreiser why don't you clone the origin of this pull request, i.e. https://github.com/MykolaMykhno/upx-testsuite ?

**Pull request closed without merging**
